spring:
  application:
    name: uaa-service
    
server:
  context-path: /uaa
  use-forward-headers: false
  
eureka:
  instance:
    hostname: eureka-client-micro.herokuapp.com
  client:
    serviceUrl:
      defaultZone: https://user:password@eureka-micro.herokuapp.com/eureka/
      
security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**
  
logging:
  level.org.springframework.security: DEBUG
